name: Deploy Static Site to GCP

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 允許手動觸發

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to GCP Instance
        run: |
          gcloud compute scp --recurse ./* ${{ secrets.GCP_INSTANCE_NAME }}:/tmp/deploy \
            --zone=${{ secrets.GCP_ZONE }}
          
          gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }} \
            --zone=${{ secrets.GCP_ZONE }} \
            --command="
              sudo rm -rf /var/www/html/* &&
              sudo cp -r /tmp/deploy/* /var/www/html/ &&
              sudo chown -R www-data:www-data /var/www/html &&
              sudo systemctl reload nginx &&
              rm -rf /tmp/deploy
            "

      - name: Verify Deployment
        run: |
          echo "Static site deployed successfully!"
          echo "Access your site at: http://$(gcloud compute instances describe ${{ secrets.GCP_INSTANCE_NAME }} --zone=${{ secrets.GCP_ZONE }} --format='get(networkInterfaces[0].accessConfigs[0].natIP)')"